[versions]
agp = "8.13.2"
kotlin = "2.3.10"

[libraries]
material = { group = "com.google.android.material", name = "material", version = "1.13.0" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
core = { group = "androidx.core", name = "core", version = "1.17.0" }
core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version = "2.9.7" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version = "2.9.7" }
editor = { module = "io.github.rosemoe:editor", version = "0.24.4" }
language-java = { module = "io.github.rosemoe:language-java", version = "0.24.4" }
dalvik-dx = { module = "com.jakewharton.android.repackaged:dalvik-dx", version = "16.0.1" }
androidx-junit = { module = "androidx.test.ext:junit", version = "1.3.0" }
androidx-runner = { module = "androidx.test:runner", version = "1.7.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
